name: prueba
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.0.0
  claude_dart_flutter: ^1.0.0+1
  flutter_html: ^2.0.0 
  google_fonts: 6.2.1
  connectivity_plus: ^2.3.0
  connectivity: ^3.0.6
  firebase_core: ^2.4.1
  firebase_auth: ^4.6.1
  firebase_analytics: ^10.3.1
  cloud_firestore: ^4.0.0
  intl: ^0.18.0 
  cupertino_icons: ^1.0.6
  google_generative_ai: ^0.4.3
  flutter_tts: ^3.5.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0

  

flutter:
  
  uses-material-design: true
  assets:
    - lib/images/fondo.jpeg
    - lib/images/login.jpg
    - lib/images/Virginia.jpg
